export const EMOJI_CATEGORIES = [
    { id: 'smileys',    label: 'Cảm xúc' },
    { id: 'people',     label: 'Con người' },
    { id: 'animals',    label: 'Động vật' },
    { id: 'food',       label: 'Đồ ăn' },
    { id: 'activities', label: 'Hoạt động' },
    { id: 'travel',     label: 'Du lịch' },
    { id: 'objects',    label: 'Đồ vật' },
    { id: 'symbols',    label: 'Ký hiệu' },
]

export const EMOJIS = [
    // ── Smileys & emotion ──
    { char: '😀', name: 'grinning face',                category: 'smileys', keywords: ['happy', 'smile', 'vui'] },
    { char: '😃', name: 'grinning face with big eyes',  category: 'smileys', keywords: ['happy', 'smile', 'vui'] },
    { char: '😄', name: 'grinning face with smiling eyes', category: 'smileys', keywords: ['happy', 'laugh', 'cuoi'] },
    { char: '😁', name: 'beaming face',                 category: 'smileys', keywords: ['happy', 'grin', 'cuoi'] },
    { char: '😆', name: 'grinning squinting face',      category: 'smileys', keywords: ['laugh', 'haha', 'cuoi'] },
    { char: '😅', name: 'grinning face with sweat',     category: 'smileys', keywords: ['phew', 'sweat', 'toat mo hoi'] },
    { char: '🤣', name: 'rolling on the floor laughing', category: 'smileys', keywords: ['lol', 'rofl', 'cuoi lan'] },
    { char: '😂', name: 'face with tears of joy',       category: 'smileys', keywords: ['lol', 'cry laugh', 'khoc cuoi'] },
    { char: '🙂', name: 'slightly smiling face',        category: 'smileys', keywords: ['smile', 'mim cuoi'] },
    { char: '🙃', name: 'upside-down face',             category: 'smileys', keywords: ['silly', 'sarcasm'] },
    { char: '😉', name: 'winking face',                 category: 'smileys', keywords: ['wink', 'nhay mat'] },
    { char: '😊', name: 'smiling face with smiling eyes', category: 'smileys', keywords: ['happy', 'blush', 'e then'] },
    { char: '😇', name: 'smiling face with halo',       category: 'smileys', keywords: ['angel', 'innocent'] },
    { char: '🥰', name: 'smiling face with hearts',     category: 'smileys', keywords: ['love', 'yeu', 'thich'] },
    { char: '😍', name: 'heart eyes',                   category: 'smileys', keywords: ['love', 'yeu', 'thich qua'] },
    { char: '🤩', name: 'star-struck',                  category: 'smileys', keywords: ['wow', 'amazed'] },
    { char: '😘', name: 'face blowing a kiss',          category: 'smileys', keywords: ['kiss', 'hon'] },
    { char: '😗', name: 'kissing face',                 category: 'smileys', keywords: ['kiss', 'hon'] },
    { char: '😋', name: 'face savoring food',           category: 'smileys', keywords: ['yum', 'delicious', 'ngon'] },
    { char: '😛', name: 'face with tongue',             category: 'smileys', keywords: ['tongue', 'le luoi'] },
    { char: '😜', name: 'winking face with tongue',     category: 'smileys', keywords: ['tongue', 'playful'] },
    { char: '🤪', name: 'zany face',                    category: 'smileys', keywords: ['crazy', 'silly'] },
    { char: '😝', name: 'squinting face with tongue',   category: 'smileys', keywords: ['tongue', 'silly'] },
    { char: '🤑', name: 'money-mouth face',             category: 'smileys', keywords: ['money', 'rich', 'tien'] },
    { char: '🤗', name: 'hugging face',                 category: 'smileys', keywords: ['hug', 'om'] },
    { char: '🤭', name: 'face with hand over mouth',    category: 'smileys', keywords: ['oops', 'giggle'] },
    { char: '🤫', name: 'shushing face',                category: 'smileys', keywords: ['quiet', 'shh', 'im lang'] },
    { char: '🤔', name: 'thinking face',                category: 'smileys', keywords: ['think', 'suy nghi'] },
    { char: '🤐', name: 'zipper-mouth face',            category: 'smileys', keywords: ['silent', 'secret'] },
    { char: '🤨', name: 'face with raised eyebrow',     category: 'smileys', keywords: ['suspicious', 'nghi ngo'] },
    { char: '😐', name: 'neutral face',                 category: 'smileys', keywords: ['meh', 'binh thuong'] },
    { char: '😑', name: 'expressionless face',          category: 'smileys', keywords: ['blank', 'vo cam'] },
    { char: '😶', name: 'face without mouth',           category: 'smileys', keywords: ['silent', 'khong noi'] },
    { char: '😏', name: 'smirking face',                category: 'smileys', keywords: ['smug', 'cham choc'] },
    { char: '😒', name: 'unamused face',                category: 'smileys', keywords: ['annoyed', 'kho chiu'] },
    { char: '🙄', name: 'face with rolling eyes',       category: 'smileys', keywords: ['eyeroll', 'chan'] },
    { char: '😬', name: 'grimacing face',               category: 'smileys', keywords: ['awkward', 'gong'] },
    { char: '😔', name: 'pensive face',                 category: 'smileys', keywords: ['sad', 'buon'] },
    { char: '😪', name: 'sleepy face',                  category: 'smileys', keywords: ['tired', 'buon ngu'] },
    { char: '🤤', name: 'drooling face',                category: 'smileys', keywords: ['drool', 'them'] },
    { char: '😴', name: 'sleeping face',                category: 'smileys', keywords: ['sleep', 'ngu'] },
    { char: '😷', name: 'face with medical mask',       category: 'smileys', keywords: ['sick', 'mask', 'khau trang'] },
    { char: '🤒', name: 'face with thermometer',        category: 'smileys', keywords: ['sick', 'fever', 'benh'] },
    { char: '🤕', name: 'face with head-bandage',       category: 'smileys', keywords: ['hurt', 'dau'] },
    { char: '🤢', name: 'nauseated face',               category: 'smileys', keywords: ['sick', 'buon non'] },
    { char: '🤮', name: 'face vomiting',                category: 'smileys', keywords: ['vomit', 'non'] },
    { char: '🥵', name: 'hot face',                     category: 'smileys', keywords: ['hot', 'nong'] },
    { char: '🥶', name: 'cold face',                    category: 'smileys', keywords: ['cold', 'lanh'] },
    { char: '😵', name: 'dizzy face',                   category: 'smileys', keywords: ['dizzy', 'choang'] },
    { char: '🤯', name: 'exploding head',               category: 'smileys', keywords: ['mindblown', 'shock'] },
    { char: '🥳', name: 'partying face',                category: 'smileys', keywords: ['party', 'an mung'] },
    { char: '😎', name: 'smiling face with sunglasses', category: 'smileys', keywords: ['cool', 'ngau'] },
    { char: '🤓', name: 'nerd face',                    category: 'smileys', keywords: ['nerd', 'geek'] },
    { char: '🧐', name: 'face with monocle',            category: 'smileys', keywords: ['inspect', 'xem xet'] },
    { char: '😕', name: 'confused face',                category: 'smileys', keywords: ['confused', 'boi roi'] },
    { char: '😟', name: 'worried face',                 category: 'smileys', keywords: ['worried', 'lo lang'] },
    { char: '🙁', name: 'slightly frowning face',       category: 'smileys', keywords: ['sad', 'buon'] },
    { char: '😮', name: 'face with open mouth',         category: 'smileys', keywords: ['surprised', 'ngac nhien'] },
    { char: '😯', name: 'hushed face',                  category: 'smileys', keywords: ['surprised', 'bat ngo'] },
    { char: '😲', name: 'astonished face',              category: 'smileys', keywords: ['shocked', 'soc'] },
    { char: '😳', name: 'flushed face',                 category: 'smileys', keywords: ['embarrassed', 'do mat'] },
    { char: '🥺', name: 'pleading face',                category: 'smileys', keywords: ['puppy eyes', 'nan ni'] },
    { char: '😦', name: 'frowning face with open mouth', category: 'smileys', keywords: ['scared', 'so'] },
    { char: '😧', name: 'anguished face',               category: 'smileys', keywords: ['pain', 'dau kho'] },
    { char: '😨', name: 'fearful face',                 category: 'smileys', keywords: ['fear', 'so hai'] },
    { char: '😰', name: 'anxious face with sweat',      category: 'smileys', keywords: ['anxious', 'lo lang'] },
    { char: '😥', name: 'sad but relieved face',        category: 'smileys', keywords: ['sad', 'buon'] },
    { char: '😢', name: 'crying face',                  category: 'smileys', keywords: ['cry', 'khoc'] },
    { char: '😭', name: 'loudly crying face',           category: 'smileys', keywords: ['sob', 'khoc to'] },
    { char: '😱', name: 'face screaming in fear',       category: 'smileys', keywords: ['scream', 'hoang loan'] },
    { char: '😖', name: 'confounded face',              category: 'smileys', keywords: ['frustrated', 'kho chiu'] },
    { char: '😣', name: 'persevering face',             category: 'smileys', keywords: ['struggle', 'co gang'] },
    { char: '😞', name: 'disappointed face',            category: 'smileys', keywords: ['disappointed', 'that vong'] },
    { char: '😓', name: 'downcast face with sweat',     category: 'smileys', keywords: ['tired', 'met'] },
    { char: '😩', name: 'weary face',                   category: 'smileys', keywords: ['weary', 'kiet suc'] },
    { char: '😫', name: 'tired face',                   category: 'smileys', keywords: ['tired', 'met moi'] },
    { char: '🥱', name: 'yawning face',                 category: 'smileys', keywords: ['tired', 'ngap'] },
    { char: '😤', name: 'face with steam from nose',    category: 'smileys', keywords: ['angry', 'tuc'] },
    { char: '😡', name: 'pouting face',                 category: 'smileys', keywords: ['angry', 'gian'] },
    { char: '😠', name: 'angry face',                   category: 'smileys', keywords: ['angry', 'noi gian'] },
    { char: '🤬', name: 'face with symbols on mouth',   category: 'smileys', keywords: ['cursing', 'chui'] },
    { char: '😈', name: 'smiling face with horns',      category: 'smileys', keywords: ['devil', 'ranh ma'] },
    { char: '👿', name: 'angry face with horns',        category: 'smileys', keywords: ['devil', 'angry'] },
    { char: '💀', name: 'skull',                        category: 'smileys', keywords: ['dead', 'chet'] },
    { char: '❤️', name: 'red heart',                    category: 'smileys', keywords: ['love', 'yeu', 'tim'] },
    { char: '🧡', name: 'orange heart',                 category: 'smileys', keywords: ['love', 'tim cam'] },
    { char: '💛', name: 'yellow heart',                 category: 'smileys', keywords: ['love', 'tim vang'] },
    { char: '💚', name: 'green heart',                  category: 'smileys', keywords: ['love', 'tim xanh'] },
    { char: '💙', name: 'blue heart',                   category: 'smileys', keywords: ['love', 'tim xanh duong'] },
    { char: '💜', name: 'purple heart',                 category: 'smileys', keywords: ['love', 'tim tim'] },
    { char: '🖤', name: 'black heart',                  category: 'smileys', keywords: ['love', 'tim den'] },
    { char: '💔', name: 'broken heart',                 category: 'smileys', keywords: ['heartbreak', 'tan vo'] },
    { char: '💕', name: 'two hearts',                   category: 'smileys', keywords: ['love', 'yeu thuong'] },
    { char: '💖', name: 'sparkling heart',               category: 'smileys', keywords: ['love', 'lap lanh'] },
    { char: '💗', name: 'growing heart',                category: 'smileys', keywords: ['love', 'tim'] },
    { char: '💓', name: 'beating heart',                category: 'smileys', keywords: ['love', 'tim dap'] },
    { char: '💞', name: 'revolving hearts',             category: 'smileys', keywords: ['love', 'tim xoay'] },
    { char: '💘', name: 'heart with arrow',             category: 'smileys', keywords: ['love', 'cupid'] },
    { char: '💝', name: 'heart with ribbon',            category: 'smileys', keywords: ['gift', 'love'] },

    // ── People & body ──
    { char: '👋', name: 'waving hand',                  category: 'people', keywords: ['wave', 'hi', 'chao'] },
    { char: '🤚', name: 'raised back of hand',          category: 'people', keywords: ['hand', 'stop'] },
    { char: '🖐️', name: 'hand with fingers splayed',    category: 'people', keywords: ['hand', 'high five'] },
    { char: '✋', name: 'raised hand',                   category: 'people', keywords: ['stop', 'dung lai'] },
    { char: '👌', name: 'ok hand',                      category: 'people', keywords: ['ok', 'dong y'] },
    { char: '🤌', name: 'pinched fingers',              category: 'people', keywords: ['what', 'chi vay'] },
    { char: '✌️', name: 'victory hand',                 category: 'people', keywords: ['peace', 'victory'] },
    { char: '🤞', name: 'crossed fingers',              category: 'people', keywords: ['luck', 'hy vong'] },
    { char: '🤟', name: 'love-you gesture',             category: 'people', keywords: ['love', 'yeu'] },
    { char: '🤘', name: 'sign of the horns',            category: 'people', keywords: ['rock', 'metal'] },
    { char: '👈', name: 'backhand index pointing left', category: 'people', keywords: ['point', 'chi trai'] },
    { char: '👉', name: 'backhand index pointing right', category: 'people', keywords: ['point', 'chi phai'] },
    { char: '👆', name: 'backhand index pointing up',   category: 'people', keywords: ['point', 'chi len'] },
    { char: '👇', name: 'backhand index pointing down', category: 'people', keywords: ['point', 'chi xuong'] },
    { char: '☝️', name: 'index pointing up',            category: 'people', keywords: ['point', 'chi'] },
    { char: '👍', name: 'thumbs up',                    category: 'people', keywords: ['like', 'good', 'thich'] },
    { char: '👎', name: 'thumbs down',                  category: 'people', keywords: ['dislike', 'bad', 'ghet'] },
    { char: '✊', name: 'raised fist',                  category: 'people', keywords: ['fist', 'power'] },
    { char: '👊', name: 'oncoming fist',                category: 'people', keywords: ['punch', 'fist bump'] },
    { char: '🤛', name: 'left-facing fist',             category: 'people', keywords: ['fist bump'] },
    { char: '🤜', name: 'right-facing fist',            category: 'people', keywords: ['fist bump'] },
    { char: '👏', name: 'clapping hands',               category: 'people', keywords: ['clap', 'vo tay'] },
    { char: '🙌', name: 'raising hands',                category: 'people', keywords: ['celebrate', 'an mung'] },
    { char: '👐', name: 'open hands',                   category: 'people', keywords: ['hug', 'open'] },
    { char: '🤲', name: 'palms up together',            category: 'people', keywords: ['pray', 'cau nguyen'] },
    { char: '🙏', name: 'folded hands',                 category: 'people', keywords: ['pray', 'thanks', 'cam on'] },
    { char: '✍️', name: 'writing hand',                 category: 'people', keywords: ['write', 'viet'] },
    { char: '💅', name: 'nail polish',                  category: 'people', keywords: ['nails', 'lam mong'] },
    { char: '🤳', name: 'selfie',                       category: 'people', keywords: ['selfie', 'tu suong'] },
    { char: '💪', name: 'flexed biceps',                category: 'people', keywords: ['strong', 'khoe'] },
    { char: '🦵', name: 'leg',                          category: 'people', keywords: ['leg', 'chan'] },
    { char: '🦶', name: 'foot',                         category: 'people', keywords: ['foot', 'ban chan'] },
    { char: '👂', name: 'ear',                          category: 'people', keywords: ['ear', 'tai'] },
    { char: '👃', name: 'nose',                         category: 'people', keywords: ['nose', 'mui'] },
    { char: '🧠', name: 'brain',                        category: 'people', keywords: ['brain', 'nao'] },
    { char: '👀', name: 'eyes',                         category: 'people', keywords: ['eyes', 'mat', 'look'] },
    { char: '👶', name: 'baby',                         category: 'people', keywords: ['baby', 'em be'] },
    { char: '🧒', name: 'child',                        category: 'people', keywords: ['child', 'tre em'] },
    { char: '👦', name: 'boy',                          category: 'people', keywords: ['boy', 'con trai'] },
    { char: '👧', name: 'girl',                         category: 'people', keywords: ['girl', 'con gai'] },
    { char: '🧑', name: 'person',                       category: 'people', keywords: ['person', 'nguoi'] },
    { char: '👱', name: 'person blond hair',            category: 'people', keywords: ['person'] },
    { char: '👨', name: 'man',                          category: 'people', keywords: ['man', 'dan ong'] },
    { char: '👩', name: 'woman',                         category: 'people', keywords: ['woman', 'phu nu'] },
    { char: '🧓', name: 'older person',                 category: 'people', keywords: ['old', 'nguoi gia'] },
    { char: '👴', name: 'old man',                       category: 'people', keywords: ['old man', 'ong'] },
    { char: '👵', name: 'old woman',                    category: 'people', keywords: ['old woman', 'ba'] },
    { char: '🙋', name: 'person raising hand',           category: 'people', keywords: ['question', 'gio tay'] },
    { char: '🙇', name: 'person bowing',                category: 'people', keywords: ['bow', 'cui chao'] },
    { char: '💁', name: 'person tipping hand',          category: 'people', keywords: ['info', 'huong dan'] },
    { char: '🙆', name: 'person gesturing ok',          category: 'people', keywords: ['ok', 'dong y'] },
    { char: '🙅', name: 'person gesturing no',          category: 'people', keywords: ['no', 'khong'] },
    { char: '🧍', name: 'person standing',              category: 'people', keywords: ['stand', 'dung'] },
    { char: '🚶', name: 'person walking',               category: 'people', keywords: ['walk', 'di bo'] },
    { char: '🏃', name: 'person running',               category: 'people', keywords: ['run', 'chay'] },
    { char: '💃', name: 'woman dancing',                category: 'people', keywords: ['dance', 'nhay'] },
    { char: '🕺', name: 'man dancing',                  category: 'people', keywords: ['dance', 'nhay'] },
    { char: '👫', name: 'woman and man holding hands',  category: 'people', keywords: ['couple', 'cap doi'] },
    { char: '👪', name: 'family',                       category: 'people', keywords: ['family', 'gia dinh'] },

    // ── Animals & nature ──
    { char: '🐶', name: 'dog face',                     category: 'animals', keywords: ['dog', 'cho'] },
    { char: '🐱', name: 'cat face',                     category: 'animals', keywords: ['cat', 'meo'] },
    { char: '🐭', name: 'mouse face',                   category: 'animals', keywords: ['mouse', 'chuot'] },
    { char: '🐹', name: 'hamster face',                 category: 'animals', keywords: ['hamster'] },
    { char: '🐰', name: 'rabbit face',                  category: 'animals', keywords: ['rabbit', 'tho'] },
    { char: '🦊', name: 'fox face',                     category: 'animals', keywords: ['fox', 'cao'] },
    { char: '🐻', name: 'bear face',                    category: 'animals', keywords: ['bear', 'gau'] },
    { char: '🐼', name: 'panda face',                   category: 'animals', keywords: ['panda'] },
    { char: '🐨', name: 'koala',                        category: 'animals', keywords: ['koala'] },
    { char: '🐯', name: 'tiger face',                   category: 'animals', keywords: ['tiger', 'ho'] },
    { char: '🦁', name: 'lion face',                    category: 'animals', keywords: ['lion', 'su tu'] },
    { char: '🐮', name: 'cow face',                     category: 'animals', keywords: ['cow', 'bo'] },
    { char: '🐷', name: 'pig face',                     category: 'animals', keywords: ['pig', 'heo'] },
    { char: '🐸', name: 'frog face',                    category: 'animals', keywords: ['frog', 'ech'] },
    { char: '🐵', name: 'monkey face',                  category: 'animals', keywords: ['monkey', 'khi'] },
    { char: '🐔', name: 'chicken',                      category: 'animals', keywords: ['chicken', 'ga'] },
    { char: '🐧', name: 'penguin',                      category: 'animals', keywords: ['penguin', 'chim canh cut'] },
    { char: '🐦', name: 'bird',                         category: 'animals', keywords: ['bird', 'chim'] },
    { char: '🐤', name: 'baby chick',                   category: 'animals', keywords: ['chick', 'ga con'] },
    { char: '🦆', name: 'duck',                         category: 'animals', keywords: ['duck', 'vit'] },
    { char: '🦅', name: 'eagle',                        category: 'animals', keywords: ['eagle', 'dai bang'] },
    { char: '🦉', name: 'owl',                          category: 'animals', keywords: ['owl', 'cu'] },
    { char: '🐺', name: 'wolf face',                    category: 'animals', keywords: ['wolf', 'soi'] },
    { char: '🐗', name: 'boar',                         category: 'animals', keywords: ['boar', 'lon rung'] },
    { char: '🐴', name: 'horse face',                   category: 'animals', keywords: ['horse', 'ngua'] },
    { char: '🦄', name: 'unicorn',                      category: 'animals', keywords: ['unicorn', 'ky lan'] },
    { char: '🐝', name: 'honeybee',                     category: 'animals', keywords: ['bee', 'ong'] },
    { char: '🐛', name: 'bug',                          category: 'animals', keywords: ['bug', 'sau'] },
    { char: '🦋', name: 'butterfly',                    category: 'animals', keywords: ['butterfly', 'buom'] },
    { char: '🐌', name: 'snail',                        category: 'animals', keywords: ['snail', 'oc sen'] },
    { char: '🐞', name: 'lady beetle',                  category: 'animals', keywords: ['ladybug', 'bo rua'] },
    { char: '🐢', name: 'turtle',                       category: 'animals', keywords: ['turtle', 'rua'] },
    { char: '🐍', name: 'snake',                        category: 'animals', keywords: ['snake', 'ran'] },
    { char: '🐙', name: 'octopus',                      category: 'animals', keywords: ['octopus', 'bach tuoc'] },
    { char: '🦑', name: 'squid',                        category: 'animals', keywords: ['squid', 'muc'] },
    { char: '🦀', name: 'crab',                         category: 'animals', keywords: ['crab', 'cua'] },
    { char: '🐠', name: 'tropical fish',                category: 'animals', keywords: ['fish', 'ca'] },
    { char: '🐟', name: 'fish',                         category: 'animals', keywords: ['fish', 'ca'] },
    { char: '🐳', name: 'spouting whale',               category: 'animals', keywords: ['whale', 'ca voi'] },
    { char: '🐬', name: 'dolphin',                      category: 'animals', keywords: ['dolphin', 'ca heo'] },
    { char: '🌸', name: 'cherry blossom',               category: 'animals', keywords: ['flower', 'hoa'] },
    { char: '🌹', name: 'rose',                         category: 'animals', keywords: ['rose', 'hoa hong'] },
    { char: '🌻', name: 'sunflower',                    category: 'animals', keywords: ['sunflower', 'hoa huong duong'] },
    { char: '🌴', name: 'palm tree',                    category: 'animals', keywords: ['tree', 'cay'] },
    { char: '🌵', name: 'cactus',                       category: 'animals', keywords: ['cactus', 'xuong rong'] },
    { char: '🍀', name: 'four leaf clover',             category: 'animals', keywords: ['luck', 'may man'] },
    { char: '🌈', name: 'rainbow',                      category: 'animals', keywords: ['rainbow', 'cau vong'] },
    { char: '☀️', name: 'sun',                          category: 'animals', keywords: ['sun', 'mat troi'] },
    { char: '🌙', name: 'crescent moon',                category: 'animals', keywords: ['moon', 'mat trang'] },
    { char: '⭐', name: 'star',                         category: 'animals', keywords: ['star', 'sao'] },
    { char: '🔥', name: 'fire',                         category: 'animals', keywords: ['fire', 'lua', 'hot'] },
    { char: '💧', name: 'droplet',                      category: 'animals', keywords: ['water', 'nuoc'] },

    // ── Food & drink ──
    { char: '🍏', name: 'green apple',                  category: 'food', keywords: ['apple', 'tao'] },
    { char: '🍎', name: 'red apple',                    category: 'food', keywords: ['apple', 'tao'] },
    { char: '🍊', name: 'tangerine',                    category: 'food', keywords: ['orange', 'cam'] },
    { char: '🍋', name: 'lemon',                        category: 'food', keywords: ['lemon', 'chanh'] },
    { char: '🍌', name: 'banana',                       category: 'food', keywords: ['banana', 'chuoi'] },
    { char: '🍉', name: 'watermelon',                   category: 'food', keywords: ['watermelon', 'dua hau'] },
    { char: '🍇', name: 'grapes',                       category: 'food', keywords: ['grapes', 'nho'] },
    { char: '🍓', name: 'strawberry',                   category: 'food', keywords: ['strawberry', 'dau tay'] },
    { char: '🍈', name: 'melon',                        category: 'food', keywords: ['melon', 'dua'] },
    { char: '🍒', name: 'cherries',                     category: 'food', keywords: ['cherry', 'anh dao'] },
    { char: '🍑', name: 'peach',                        category: 'food', keywords: ['peach', 'dao'] },
    { char: '🥭', name: 'mango',                        category: 'food', keywords: ['mango', 'xoai'] },
    { char: '🍍', name: 'pineapple',                    category: 'food', keywords: ['pineapple', 'thom'] },
    { char: '🥥', name: 'coconut',                      category: 'food', keywords: ['coconut', 'dua'] },
    { char: '🥝', name: 'kiwi fruit',                   category: 'food', keywords: ['kiwi'] },
    { char: '🍅', name: 'tomato',                       category: 'food', keywords: ['tomato', 'ca chua'] },
    { char: '🥑', name: 'avocado',                      category: 'food', keywords: ['avocado', 'bo'] },
    { char: '🌽', name: 'ear of corn',                  category: 'food', keywords: ['corn', 'ngo'] },
    { char: '🥕', name: 'carrot',                       category: 'food', keywords: ['carrot', 'ca rot'] },
    { char: '🍞', name: 'bread',                        category: 'food', keywords: ['bread', 'banh mi'] },
    { char: '🥐', name: 'croissant',                    category: 'food', keywords: ['croissant'] },
    { char: '🧀', name: 'cheese wedge',                 category: 'food', keywords: ['cheese', 'pho mai'] },
    { char: '🍖', name: 'meat on bone',                 category: 'food', keywords: ['meat', 'thit'] },
    { char: '🍗', name: 'poultry leg',                  category: 'food', keywords: ['chicken', 'ga'] },
    { char: '🍔', name: 'hamburger',                    category: 'food', keywords: ['burger', 'hamburger'] },
    { char: '🍟', name: 'french fries',                 category: 'food', keywords: ['fries', 'khoai tay chien'] },
    { char: '🍕', name: 'pizza',                        category: 'food', keywords: ['pizza'] },
    { char: '🌭', name: 'hot dog',                      category: 'food', keywords: ['hotdog'] },
    { char: '🥪', name: 'sandwich',                     category: 'food', keywords: ['sandwich', 'banh mi kep'] },
    { char: '🌮', name: 'taco',                         category: 'food', keywords: ['taco'] },
    { char: '🍿', name: 'popcorn',                      category: 'food', keywords: ['popcorn', 'bap rang'] },
    { char: '🍳', name: 'cooking',                      category: 'food', keywords: ['egg', 'trung chien'] },
    { char: '🍜', name: 'steaming bowl',                category: 'food', keywords: ['noodle', 'pho', 'mi'] },
    { char: '🍲', name: 'pot of food',                  category: 'food', keywords: ['soup', 'canh'] },
    { char: '🍱', name: 'bento box',                    category: 'food', keywords: ['bento'] },
    { char: '🍣', name: 'sushi',                        category: 'food', keywords: ['sushi'] },
    { char: '🍤', name: 'fried shrimp',                 category: 'food', keywords: ['shrimp', 'tom'] },
    { char: '🍙', name: 'rice ball',                    category: 'food', keywords: ['rice', 'com nam'] },
    { char: '🍚', name: 'cooked rice',                  category: 'food', keywords: ['rice', 'com'] },
    { char: '🍘', name: 'rice cracker',                 category: 'food', keywords: ['cracker', 'banh gao'] },
    { char: '🥟', name: 'dumpling',                     category: 'food', keywords: ['dumpling', 'banh bao'] },
    { char: '🍦', name: 'soft ice cream',               category: 'food', keywords: ['ice cream', 'kem'] },
    { char: '🍨', name: 'ice cream',                    category: 'food', keywords: ['ice cream', 'kem'] },
    { char: '🍧', name: 'shaved ice',                   category: 'food', keywords: ['shaved ice', 'da bao'] },
    { char: '🎂', name: 'birthday cake',                category: 'food', keywords: ['cake', 'banh sinh nhat'] },
    { char: '🍰', name: 'shortcake',                    category: 'food', keywords: ['cake', 'banh'] },
    { char: '🧁', name: 'cupcake',                      category: 'food', keywords: ['cupcake', 'banh cup'] },
    { char: '🍫', name: 'chocolate bar',                category: 'food', keywords: ['chocolate', 'socola'] },
    { char: '🍬', name: 'candy',                        category: 'food', keywords: ['candy', 'keo'] },
    { char: '🍭', name: 'lollipop',                     category: 'food', keywords: ['lollipop', 'keo mut'] },
    { char: '☕', name: 'hot beverage',                 category: 'food', keywords: ['coffee', 'ca phe'] },
    { char: '🍵', name: 'teacup without handle',        category: 'food', keywords: ['tea', 'tra'] },
    { char: '🧋', name: 'bubble tea',                   category: 'food', keywords: ['boba', 'tra sua'] },
    { char: '🥤', name: 'cup with straw',               category: 'food', keywords: ['drink', 'nuoc'] },
    { char: '🧃', name: 'beverage box',                 category: 'food', keywords: ['juice', 'nuoc ep'] },
    { char: '🍺', name: 'beer mug',                     category: 'food', keywords: ['beer', 'bia'] },
    { char: '🍻', name: 'clinking beer mugs',           category: 'food', keywords: ['cheers', 'chuc mung'] },
    { char: '🍷', name: 'wine glass',                   category: 'food', keywords: ['wine', 'ruou vang'] },
    { char: '🍸', name: 'cocktail glass',               category: 'food', keywords: ['cocktail'] },
    { char: '🥂', name: 'clinking glasses',             category: 'food', keywords: ['cheers', 'chuc mung'] },

    // ── Activities ──
    { char: '⚽', name: 'soccer ball',                  category: 'activities', keywords: ['football', 'bong da'] },
    { char: '🏀', name: 'basketball',                   category: 'activities', keywords: ['basketball', 'bong ro'] },
    { char: '🏈', name: 'american football',            category: 'activities', keywords: ['football'] },
    { char: '⚾', name: 'baseball',                     category: 'activities', keywords: ['baseball'] },
    { char: '🎾', name: 'tennis',                       category: 'activities', keywords: ['tennis'] },
    { char: '🏐', name: 'volleyball',                   category: 'activities', keywords: ['volleyball', 'bong chuyen'] },
    { char: '🏓', name: 'ping pong',                    category: 'activities', keywords: ['ping pong', 'bong ban'] },
    { char: '🏸', name: 'badminton',                    category: 'activities', keywords: ['badminton', 'cau long'] },
    { char: '🥊', name: 'boxing glove',                 category: 'activities', keywords: ['boxing', 'quyen anh'] },
    { char: '🎱', name: 'pool 8 ball',                  category: 'activities', keywords: ['billiards', 'bi-a'] },
    { char: '🏆', name: 'trophy',                       category: 'activities', keywords: ['trophy', 'cup', 'chien thang'] },
    { char: '🥇', name: 'first place medal',            category: 'activities', keywords: ['gold medal', 'huy chuong vang'] },
    { char: '🎮', name: 'video game',                   category: 'activities', keywords: ['game', 'choi game'] },
    { char: '🎲', name: 'game die',                     category: 'activities', keywords: ['dice', 'xuc xac'] },
    { char: '🎯', name: 'direct hit',                   category: 'activities', keywords: ['target', 'muc tieu'] },
    { char: '🎳', name: 'bowling',                      category: 'activities', keywords: ['bowling'] },
    { char: '🎨', name: 'artist palette',               category: 'activities', keywords: ['art', 've'] },
    { char: '🎬', name: 'clapper board',                category: 'activities', keywords: ['movie', 'phim'] },
    { char: '🎤', name: 'microphone',                   category: 'activities', keywords: ['mic', 'hat'] },
    { char: '🎧', name: 'headphone',                    category: 'activities', keywords: ['music', 'nghe nhac'] },
    { char: '🎼', name: 'musical score',                category: 'activities', keywords: ['music', 'nhac'] },
    { char: '🎹', name: 'musical keyboard',             category: 'activities', keywords: ['piano', 'dan'] },
    { char: '🎸', name: 'guitar',                       category: 'activities', keywords: ['guitar'] },
    { char: '🎉', name: 'party popper',                 category: 'activities', keywords: ['party', 'an mung', 'chuc mung'] },
    { char: '🎊', name: 'confetti ball',                category: 'activities', keywords: ['party', 'confetti'] },
    { char: '🎁', name: 'wrapped gift',                 category: 'activities', keywords: ['gift', 'qua'] },

    // ── Travel & places ──
    { char: '🚗', name: 'automobile',                   category: 'travel', keywords: ['car', 'xe hoi'] },
    { char: '🚕', name: 'taxi',                         category: 'travel', keywords: ['taxi'] },
    { char: '🚌', name: 'bus',                          category: 'travel', keywords: ['bus', 'xe buyt'] },
    { char: '🏍️', name: 'motorcycle',                   category: 'travel', keywords: ['motorbike', 'xe may'] },
    { char: '🚲', name: 'bicycle',                      category: 'travel', keywords: ['bike', 'xe dap'] },
    { char: '✈️', name: 'airplane',                     category: 'travel', keywords: ['plane', 'may bay'] },
    { char: '🚀', name: 'rocket',                       category: 'travel', keywords: ['rocket', 'ten lua'] },
    { char: '🚁', name: 'helicopter',                   category: 'travel', keywords: ['helicopter', 'truc thang'] },
    { char: '🚢', name: 'ship',                         category: 'travel', keywords: ['ship', 'tau'] },
    { char: '⛵', name: 'sailboat',                     category: 'travel', keywords: ['boat', 'thuyen'] },
    { char: '🚂', name: 'locomotive',                   category: 'travel', keywords: ['train', 'tau hoa'] },
    { char: '🚦', name: 'traffic light',                category: 'travel', keywords: ['traffic', 'den giao thong'] },
    { char: '🗺️', name: 'world map',                    category: 'travel', keywords: ['map', 'ban do'] },
    { char: '🗽', name: 'statue of liberty',            category: 'travel', keywords: ['landmark'] },
    { char: '🗼', name: 'tokyo tower',                  category: 'travel', keywords: ['tower', 'thap'] },
    { char: '🏰', name: 'castle',                       category: 'travel', keywords: ['castle', 'lau dai'] },
    { char: '🏠', name: 'house',                        category: 'travel', keywords: ['house', 'nha'] },
    { char: '🏢', name: 'office building',              category: 'travel', keywords: ['office', 'toa nha'] },
    { char: '🏖️', name: 'beach with umbrella',          category: 'travel', keywords: ['beach', 'bien'] },
    { char: '🏝️', name: 'desert island',                category: 'travel', keywords: ['island', 'dao'] },
    { char: '🏔️', name: 'snow-capped mountain',         category: 'travel', keywords: ['mountain', 'nui'] },
    { char: '🌋', name: 'volcano',                      category: 'travel', keywords: ['volcano', 'nui lua'] },
    { char: '🗻', name: 'mount fuji',                   category: 'travel', keywords: ['mountain', 'nui'] },
    { char: '🎡', name: 'ferris wheel',                 category: 'travel', keywords: ['ferris wheel', 'vong quay'] },
    { char: '🎢', name: 'roller coaster',               category: 'travel', keywords: ['roller coaster'] },

    // ── Objects ──
    { char: '⌚', name: 'watch',                        category: 'objects', keywords: ['watch', 'dong ho'] },
    { char: '📱', name: 'mobile phone',                 category: 'objects', keywords: ['phone', 'dien thoai'] },
    { char: '💻', name: 'laptop',                       category: 'objects', keywords: ['laptop', 'may tinh'] },
    { char: '⌨️', name: 'keyboard',                     category: 'objects', keywords: ['keyboard', 'ban phim'] },
    { char: '🖥️', name: 'desktop computer',             category: 'objects', keywords: ['computer', 'may tinh'] },
    { char: '🖨️', name: 'printer',                      category: 'objects', keywords: ['printer', 'may in'] },
    { char: '📷', name: 'camera',                       category: 'objects', keywords: ['camera', 'may anh'] },
    { char: '📺', name: 'television',                   category: 'objects', keywords: ['tv', 'ti vi'] },
    { char: '🔋', name: 'battery',                      category: 'objects', keywords: ['battery', 'pin'] },
    { char: '💡', name: 'light bulb',                   category: 'objects', keywords: ['idea', 'bong den'] },
    { char: '🔦', name: 'flashlight',                   category: 'objects', keywords: ['flashlight', 'den pin'] },
    { char: '💰', name: 'money bag',                    category: 'objects', keywords: ['money', 'tien'] },
    { char: '💵', name: 'dollar banknote',              category: 'objects', keywords: ['money', 'dollar', 'tien'] },
    { char: '💳', name: 'credit card',                  category: 'objects', keywords: ['card', 'the'] },
    { char: '📈', name: 'chart increasing',             category: 'objects', keywords: ['chart', 'tang'] },
    { char: '📉', name: 'chart decreasing',             category: 'objects', keywords: ['chart', 'giam'] },
    { char: '✉️', name: 'envelope',                     category: 'objects', keywords: ['mail', 'thu'] },
    { char: '📦', name: 'package',                      category: 'objects', keywords: ['box', 'hop', 'giao hang'] },
    { char: '📌', name: 'pushpin',                      category: 'objects', keywords: ['pin', 'ghim'] },
    { char: '📎', name: 'paperclip',                    category: 'objects', keywords: ['clip', 'ghim giay'] },
    { char: '✂️', name: 'scissors',                     category: 'objects', keywords: ['scissors', 'keo'] },
    { char: '🔒', name: 'locked',                       category: 'objects', keywords: ['lock', 'khoa'] },
    { char: '🔑', name: 'key',                          category: 'objects', keywords: ['key', 'chia khoa'] },
    { char: '🔨', name: 'hammer',                       category: 'objects', keywords: ['hammer', 'bua'] },
    { char: '🔧', name: 'wrench',                       category: 'objects', keywords: ['wrench', 'co le'] },
    { char: '💊', name: 'pill',                         category: 'objects', keywords: ['medicine', 'thuoc'] },
    { char: '🎁', name: 'gift',                         category: 'objects', keywords: ['gift', 'qua'] },
    { char: '🎈', name: 'balloon',                       category: 'objects', keywords: ['balloon', 'bong bay'] },

    // ── Symbols ──
    { char: '✅', name: 'check mark button',            category: 'symbols', keywords: ['done', 'ok', 'xong'] },
    { char: '❌', name: 'cross mark',                   category: 'symbols', keywords: ['no', 'sai', 'huy'] },
    { char: '❓', name: 'question mark',                category: 'symbols', keywords: ['question', 'hoi'] },
    { char: '❗', name: 'exclamation mark',             category: 'symbols', keywords: ['warning', 'chu y'] },
    { char: '⚠️', name: 'warning',                      category: 'symbols', keywords: ['warning', 'canh bao'] },
    { char: '🔴', name: 'red circle',                   category: 'symbols', keywords: ['red', 'do'] },
    { char: '🟢', name: 'green circle',                 category: 'symbols', keywords: ['green', 'xanh'] },
    { char: '🟡', name: 'yellow circle',                category: 'symbols', keywords: ['yellow', 'vang'] },
    { char: '🔵', name: 'blue circle',                  category: 'symbols', keywords: ['blue', 'xanh duong'] },
    { char: '⭐', name: 'star',                         category: 'symbols', keywords: ['star', 'sao'] },
    { char: '✨', name: 'sparkles',                     category: 'symbols', keywords: ['sparkle', 'lap lanh'] },
    { char: '💯', name: 'hundred points',               category: 'symbols', keywords: ['100', 'perfect'] },
    { char: '🔞', name: 'no one under eighteen',        category: 'symbols', keywords: ['18+'] },
    { char: '🆗', name: 'ok button',                    category: 'symbols', keywords: ['ok'] },
    { char: '🆕', name: 'new button',                   category: 'symbols', keywords: ['new', 'moi'] },
    { char: '🔁', name: 'repeat button',                category: 'symbols', keywords: ['repeat', 'lap lai'] },
    { char: '▶️', name: 'play button',                  category: 'symbols', keywords: ['play', 'phat'] },
    { char: '⏸️', name: 'pause button',                 category: 'symbols', keywords: ['pause', 'tam dung'] },
    { char: '🔔', name: 'bell',                         category: 'symbols', keywords: ['bell', 'chuong', 'notify'] },
    { char: '🔇', name: 'muted speaker',                category: 'symbols', keywords: ['mute', 'im lang'] },
]
