export const occasions = {
  "vi": {
    "corporate": "Quà doanh nghiệp",
    "birthday": "Sinh nhật",
    "christmas": "Noel - Giáng Sinh",
    "new-year": "Tết Dương lịch",
    "lunar-new-year": "Tết Nguyên Đán",
    "mid-autumn-festival": "Tết Trung Thu",
    "valentines-day": "Valentine - 14/2",
    "international-womens-day": "Quốc tế Phụ nữ - 8/3",
    "vietnamese-womens-day": "Ngày Phụ nữ Việt Nam - 20/10",
    "vietnamese-teachers-day": "Ngày Nhà giáo Việt Nam - 20/11",
    "childrens-day": "Quốc tế Thiếu nhi - 1/6",
    "anniversary": "Ngày kỷ niệm",
    "dating-anniversary": "Kỷ niệm yêu nhau",
    "wedding-anniversary": "Kỷ niệm ngày cưới",
    "mothers-day": "Ngày của Mẹ",
    "fathers-day": "Ngày của Cha",
    "international-day-of-happiness": "Ngày Quốc tế Hạnh phúc",
    "vietnamese-family-day": "Ngày Gia đình Việt Nam",
    "wedding": "Đám cưới",
    "engagement": "Đính hôn",
    "proposal": "Cầu hôn",
    "full-month-celebration": "Mừng đầy tháng",
    "first-birthday": "Mừng thôi nôi",
    "new-baby": "Mừng sinh con",
    "graduation": "Tốt nghiệp",
    "grand-opening": "Khai trương",
    "housewarming": "Tân gia",
    "promotion": "Thăng chức",
    "new-job": "Công việc mới",
    "thank-you": "Quà cảm ơn",
    "apology": "Quà xin lỗi",
    "congratulations": "Quà chúc mừng",
    "encouragement": "Quà động viên",
    "farewell": "Quà chia tay",
    "client-partner-appreciation": "Quà tri ân khách hàng / đối tác",
    "surprise-gift": "Quà bất ngờ"
  },
  "en": {
    "corporate": "Corporate Gift",
    "birthday": "Birthday",
    "christmas": "Christmas",
    "new-year": "New Year's Day",
    "lunar-new-year": "Lunar New Year",
    "mid-autumn-festival": "Mid-Autumn Festival",
    "valentines-day": "Valentine's Day - February 14",
    "international-womens-day": "International Women's Day - March 8",
    "vietnamese-womens-day": "Vietnamese Women's Day - October 20",
    "vietnamese-teachers-day": "Vietnamese Teachers' Day - November 20",
    "childrens-day": "International Children's Day - June 1",
    "anniversary": "Anniversary",
    "dating-anniversary": "Dating Anniversary",
    "wedding-anniversary": "Wedding Anniversary",
    "mothers-day": "Mother's Day",
    "fathers-day": "Father's Day",
    "international-day-of-happiness": "International Day of Happiness",
    "vietnamese-family-day": "Vietnamese Family Day",
    "wedding": "Wedding",
    "engagement": "Engagement",
    "proposal": "Marriage Proposal",
    "full-month-celebration": "Baby's One-Month Celebration",
    "first-birthday": "First Birthday Celebration",
    "new-baby": "New Baby",
    "graduation": "Graduation",
    "grand-opening": "Grand Opening",
    "housewarming": "Housewarming",
    "promotion": "Promotion",
    "new-job": "New Job",
    "thank-you": "Thank You Gift",
    "apology": "Apology Gift",
    "congratulations": "Congratulations Gift",
    "encouragement": "Encouragement Gift",
    "farewell": "Farewell Gift",
    "client-partner-appreciation": "Client / Partner Appreciation Gift",
    "surprise-gift": "Surprise Gift"
  }
}

export const colorTypes = {
  "vi": {
    "beige": "Be",
    "black": "Đen",
    "red": "Đỏ",
    "pink": "Hồng",
    "brown": "Nâu",
    "purple": "Tím",
    "white": "Trắng",
    "yellow": "Vàng",
    "gray": "Xám",
    "blue": "Xanh dương",
    "green": "Xanh lá"
  },
  "en": {
    "beige": "Beige",
    "black": "Black",
    "red": "Red",
    "pink": "Pink",
    "brown": "Brown",
    "purple": "Purple",
    "white": "White",
    "yellow": "Yellow",
    "gray": "Gray",
    "blue": "Blue",
    "green": "Green"
  }
}
